export const SET_GLOBAL_ERROR = 'SET_GOBAL_ERROR'

export const SAVE_LOGGED_IN_USER_DATA = 'SAVE_LOGGED_IN_USER_DATA';
export const SAVE_AUTH_TOKENS = 'SAVE_AUTH_TOKENS'
// For Assets form
export const ADD_ASSET = 'ADD_ASSET'
export const ADD_CASH = 'ADD_CASH'
export const ADD_CRYPTOCURRENCY = 'ADD_CRYPTOCURRENCY'
export const ADD_FIXED_ASSET = 'ADD_FIXED_ASSET'
export const ADD_STOCK = 'ADD_STOCK'